# Generated by Django 3.2 on 2022-12-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AddField(
            model_name='food',
            name='ingredients',
            field=models.ManyToManyField(through='ordering_app.Order', to='ordering_app.Ingredient'),
        ),
        migrations.AlterField(
            model_name='client',
            name='card_number',
            field=models.CharField(max_length=16, verbose_name='Номер карточки'),
        ),
        migrations.AlterModelTable(
            name='ingredient',
            table='ingredients',
        ),
    ]
